// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.2
// source: pkg/pb/travel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Travel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TravelledCountriesCode string `protobuf:"bytes,2,opt,name=TravelledCountriesCode,proto3" json:"TravelledCountriesCode,omitempty"`
	Total                  int64  `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	CreatedAt              string `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt              string `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Deleted                string `protobuf:"bytes,6,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
}

func (x *Travel) Reset() {
	*x = Travel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Travel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Travel) ProtoMessage() {}

func (x *Travel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Travel.ProtoReflect.Descriptor instead.
func (*Travel) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{0}
}

func (x *Travel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Travel) GetTravelledCountriesCode() string {
	if x != nil {
		return x.TravelledCountriesCode
	}
	return ""
}

func (x *Travel) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Travel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Travel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Travel) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

type TravelHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64               `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size  int64               `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Query *TravelHeader_Query `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Sort  *TravelHeader_Sort  `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *TravelHeader) Reset() {
	*x = TravelHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TravelHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelHeader) ProtoMessage() {}

func (x *TravelHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelHeader.ProtoReflect.Descriptor instead.
func (*TravelHeader) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{1}
}

func (x *TravelHeader) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TravelHeader) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TravelHeader) GetQuery() *TravelHeader_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *TravelHeader) GetSort() *TravelHeader_Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

// Get
type GetTravelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GET_TRAVEL *GetTravelRequestData `protobuf:"bytes,1,opt,name=GET_TRAVEL,json=GETTRAVEL,proto3" json:"GET_TRAVEL,omitempty"`
}

func (x *GetTravelRequest) Reset() {
	*x = GetTravelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTravelRequest) ProtoMessage() {}

func (x *GetTravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTravelRequest.ProtoReflect.Descriptor instead.
func (*GetTravelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{2}
}

func (x *GetTravelRequest) GetGET_TRAVEL() *GetTravelRequestData {
	if x != nil {
		return x.GET_TRAVEL
	}
	return nil
}

type GetTravelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GET_TRAVEL *GetTravelResponseData `protobuf:"bytes,1,opt,name=GET_TRAVEL,json=GETTRAVEL,proto3" json:"GET_TRAVEL,omitempty"`
}

func (x *GetTravelResponse) Reset() {
	*x = GetTravelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTravelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTravelResponse) ProtoMessage() {}

func (x *GetTravelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTravelResponse.ProtoReflect.Descriptor instead.
func (*GetTravelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{3}
}

func (x *GetTravelResponse) GetGET_TRAVEL() *GetTravelResponseData {
	if x != nil {
		return x.GET_TRAVEL
	}
	return nil
}

// Gets
type GetsTravelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GETS_TRAVEL *TravelHeader `protobuf:"bytes,1,opt,name=GETS_TRAVEL,json=GETSTRAVEL,proto3" json:"GETS_TRAVEL,omitempty"`
}

func (x *GetsTravelRequest) Reset() {
	*x = GetsTravelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsTravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsTravelRequest) ProtoMessage() {}

func (x *GetsTravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsTravelRequest.ProtoReflect.Descriptor instead.
func (*GetsTravelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{4}
}

func (x *GetsTravelRequest) GetGETS_TRAVEL() *TravelHeader {
	if x != nil {
		return x.GETS_TRAVEL
	}
	return nil
}

type GetsTravelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GETS_TRAVEL *GetsTravelResponseData `protobuf:"bytes,1,opt,name=GETS_TRAVEL,json=GETSTRAVEL,proto3" json:"GETS_TRAVEL,omitempty"`
}

func (x *GetsTravelResponse) Reset() {
	*x = GetsTravelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsTravelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsTravelResponse) ProtoMessage() {}

func (x *GetsTravelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsTravelResponse.ProtoReflect.Descriptor instead.
func (*GetsTravelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{5}
}

func (x *GetsTravelResponse) GetGETS_TRAVEL() *GetsTravelResponseData {
	if x != nil {
		return x.GETS_TRAVEL
	}
	return nil
}

// Create
type CreateTravelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CREATE_TRAVEL *Travel `protobuf:"bytes,1,opt,name=CREATE_TRAVEL,json=CREATETRAVEL,proto3" json:"CREATE_TRAVEL,omitempty"`
}

func (x *CreateTravelRequest) Reset() {
	*x = CreateTravelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTravelRequest) ProtoMessage() {}

func (x *CreateTravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTravelRequest.ProtoReflect.Descriptor instead.
func (*CreateTravelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTravelRequest) GetCREATE_TRAVEL() *Travel {
	if x != nil {
		return x.CREATE_TRAVEL
	}
	return nil
}

type CreateTravelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CREATE_TRAVEL *CreateTravelResponseData `protobuf:"bytes,1,opt,name=CREATE_TRAVEL,json=CREATETRAVEL,proto3" json:"CREATE_TRAVEL,omitempty"`
}

func (x *CreateTravelResponse) Reset() {
	*x = CreateTravelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTravelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTravelResponse) ProtoMessage() {}

func (x *CreateTravelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTravelResponse.ProtoReflect.Descriptor instead.
func (*CreateTravelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTravelResponse) GetCREATE_TRAVEL() *CreateTravelResponseData {
	if x != nil {
		return x.CREATE_TRAVEL
	}
	return nil
}

// Update
type UpdateTravelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UPDATE_TRAVEL *Travel `protobuf:"bytes,1,opt,name=UPDATE_TRAVEL,json=UPDATETRAVEL,proto3" json:"UPDATE_TRAVEL,omitempty"`
}

func (x *UpdateTravelRequest) Reset() {
	*x = UpdateTravelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTravelRequest) ProtoMessage() {}

func (x *UpdateTravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTravelRequest.ProtoReflect.Descriptor instead.
func (*UpdateTravelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTravelRequest) GetUPDATE_TRAVEL() *Travel {
	if x != nil {
		return x.UPDATE_TRAVEL
	}
	return nil
}

type UpdateTravelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UPDATE_TRAVEL *UpdateTravelResponseData `protobuf:"bytes,1,opt,name=UPDATE_TRAVEL,json=UPDATETRAVEL,proto3" json:"UPDATE_TRAVEL,omitempty"`
}

func (x *UpdateTravelResponse) Reset() {
	*x = UpdateTravelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTravelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTravelResponse) ProtoMessage() {}

func (x *UpdateTravelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTravelResponse.ProtoReflect.Descriptor instead.
func (*UpdateTravelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTravelResponse) GetUPDATE_TRAVEL() *UpdateTravelResponseData {
	if x != nil {
		return x.UPDATE_TRAVEL
	}
	return nil
}

// Delete
type DeleteTravelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DELETE_TRAVEL *DeleteTravelRequestData `protobuf:"bytes,1,opt,name=DELETE_TRAVEL,json=DELETETRAVEL,proto3" json:"DELETE_TRAVEL,omitempty"`
}

func (x *DeleteTravelRequest) Reset() {
	*x = DeleteTravelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTravelRequest) ProtoMessage() {}

func (x *DeleteTravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTravelRequest.ProtoReflect.Descriptor instead.
func (*DeleteTravelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTravelRequest) GetDELETE_TRAVEL() *DeleteTravelRequestData {
	if x != nil {
		return x.DELETE_TRAVEL
	}
	return nil
}

type DeleteTravelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DELETE_TRAVEL *DeleteTravelResponseData `protobuf:"bytes,1,opt,name=DELETE_TRAVEL,json=DELETETRAVEL,proto3" json:"DELETE_TRAVEL,omitempty"`
}

func (x *DeleteTravelResponse) Reset() {
	*x = DeleteTravelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTravelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTravelResponse) ProtoMessage() {}

func (x *DeleteTravelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTravelResponse.ProtoReflect.Descriptor instead.
func (*DeleteTravelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTravelResponse) GetDELETE_TRAVEL() *DeleteTravelResponseData {
	if x != nil {
		return x.DELETE_TRAVEL
	}
	return nil
}

type TravelHeader_Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TravelledCountriesCode string `protobuf:"bytes,2,opt,name=TravelledCountriesCode,proto3" json:"TravelledCountriesCode,omitempty"`
	Total                  int64  `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	Search                 string `protobuf:"bytes,4,opt,name=Search,proto3" json:"Search,omitempty"`
}

func (x *TravelHeader_Query) Reset() {
	*x = TravelHeader_Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TravelHeader_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelHeader_Query) ProtoMessage() {}

func (x *TravelHeader_Query) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelHeader_Query.ProtoReflect.Descriptor instead.
func (*TravelHeader_Query) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{1, 0}
}

func (x *TravelHeader_Query) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TravelHeader_Query) GetTravelledCountriesCode() string {
	if x != nil {
		return x.TravelledCountriesCode
	}
	return ""
}

func (x *TravelHeader_Query) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TravelHeader_Query) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type TravelHeader_Sort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Order string `protobuf:"bytes,2,opt,name=Order,proto3" json:"Order,omitempty"`
}

func (x *TravelHeader_Sort) Reset() {
	*x = TravelHeader_Sort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TravelHeader_Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelHeader_Sort) ProtoMessage() {}

func (x *TravelHeader_Sort) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelHeader_Sort.ProtoReflect.Descriptor instead.
func (*TravelHeader_Sort) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{1, 1}
}

func (x *TravelHeader_Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *TravelHeader_Sort) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type GetTravelRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TravelledCountriesCode string `protobuf:"bytes,2,opt,name=TravelledCountriesCode,proto3" json:"TravelledCountriesCode,omitempty"`
}

func (x *GetTravelRequestData) Reset() {
	*x = GetTravelRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTravelRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTravelRequestData) ProtoMessage() {}

func (x *GetTravelRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTravelRequestData.ProtoReflect.Descriptor instead.
func (*GetTravelRequestData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetTravelRequestData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTravelRequestData) GetTravelledCountriesCode() string {
	if x != nil {
		return x.TravelledCountriesCode
	}
	return ""
}

type GetTravelResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *Travel `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTravelResponseData) Reset() {
	*x = GetTravelResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTravelResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTravelResponseData) ProtoMessage() {}

func (x *GetTravelResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTravelResponseData.ProtoReflect.Descriptor instead.
func (*GetTravelResponseData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetTravelResponseData) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTravelResponseData) GetData() *Travel {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetsTravelResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search       string                               `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Next         bool                                 `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	Back         bool                                 `protobuf:"varint,3,opt,name=back,proto3" json:"back,omitempty"`
	Limit        int64                                `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset       int64                                `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalPage    int64                                `protobuf:"varint,6,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	CurrentPage  int64                                `protobuf:"varint,7,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	Sort         string                               `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Order        string                               `protobuf:"bytes,9,opt,name=order,proto3" json:"order,omitempty"`
	RecordsTotal int64                                `protobuf:"varint,10,opt,name=recordsTotal,proto3" json:"recordsTotal,omitempty"`
	Data         []*GetsTravelResponseData_DataTravel `protobuf:"bytes,11,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetsTravelResponseData) Reset() {
	*x = GetsTravelResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsTravelResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsTravelResponseData) ProtoMessage() {}

func (x *GetsTravelResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsTravelResponseData.ProtoReflect.Descriptor instead.
func (*GetsTravelResponseData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetsTravelResponseData) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetsTravelResponseData) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *GetsTravelResponseData) GetBack() bool {
	if x != nil {
		return x.Back
	}
	return false
}

func (x *GetsTravelResponseData) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetsTravelResponseData) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetsTravelResponseData) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *GetsTravelResponseData) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetsTravelResponseData) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetsTravelResponseData) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *GetsTravelResponseData) GetRecordsTotal() int64 {
	if x != nil {
		return x.RecordsTotal
	}
	return 0
}

func (x *GetsTravelResponseData) GetData() []*GetsTravelResponseData_DataTravel {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetsTravelResponseData_DataTravel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Total int64  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetsTravelResponseData_DataTravel) Reset() {
	*x = GetsTravelResponseData_DataTravel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetsTravelResponseData_DataTravel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsTravelResponseData_DataTravel) ProtoMessage() {}

func (x *GetsTravelResponseData_DataTravel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsTravelResponseData_DataTravel.ProtoReflect.Descriptor instead.
func (*GetsTravelResponseData_DataTravel) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *GetsTravelResponseData_DataTravel) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *GetsTravelResponseData_DataTravel) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GetsTravelResponseData_DataTravel) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateTravelResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *Travel `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateTravelResponseData) Reset() {
	*x = CreateTravelResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTravelResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTravelResponseData) ProtoMessage() {}

func (x *CreateTravelResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTravelResponseData.ProtoReflect.Descriptor instead.
func (*CreateTravelResponseData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{7, 0}
}

func (x *CreateTravelResponseData) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateTravelResponseData) GetData() *Travel {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateTravelResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *Travel `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateTravelResponseData) Reset() {
	*x = UpdateTravelResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTravelResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTravelResponseData) ProtoMessage() {}

func (x *UpdateTravelResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTravelResponseData.ProtoReflect.Descriptor instead.
func (*UpdateTravelResponseData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UpdateTravelResponseData) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateTravelResponseData) GetData() *Travel {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteTravelRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTravelRequestData) Reset() {
	*x = DeleteTravelRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTravelRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTravelRequestData) ProtoMessage() {}

func (x *DeleteTravelRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTravelRequestData.ProtoReflect.Descriptor instead.
func (*DeleteTravelRequestData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{10, 0}
}

func (x *DeleteTravelRequestData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTravelResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteTravelResponseData) Reset() {
	*x = DeleteTravelResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_travel_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTravelResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTravelResponseData) ProtoMessage() {}

func (x *DeleteTravelResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_travel_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTravelResponseData.ProtoReflect.Descriptor instead.
func (*DeleteTravelResponseData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_travel_proto_rawDescGZIP(), []int{11, 0}
}

func (x *DeleteTravelResponseData) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteTravelResponseData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pb_travel_proto protoreflect.FileDescriptor

var file_pkg_pb_travel_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x22, 0xbc, 0x01,
	0x0a, 0x06, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x6c, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c,
	0x6c, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0xca, 0x02, 0x0a,
	0x0c, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x54, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x54,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x6f, 0x72, 0x74,
	0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x1a, 0x7d, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x36, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x16, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x1a, 0x32, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xa0, 0x01, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c,
	0x0a, 0x0a, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x47, 0x45, 0x54, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x1a, 0x4e, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x6c, 0x65,
	0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x96, 0x01, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x45, 0x54, 0x5f, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x52, 0x09, 0x47, 0x45, 0x54, 0x54, 0x52, 0x41, 0x56, 0x45,
	0x4c, 0x1a, 0x42, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x73, 0x54, 0x72, 0x61,
	0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x47, 0x45,
	0x54, 0x53, 0x5f, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x47, 0x45, 0x54, 0x53, 0x54, 0x52, 0x41, 0x56, 0x45,
	0x4c, 0x22, 0xeb, 0x03, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x73, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x47, 0x45, 0x54, 0x53,
	0x5f, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x54, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0a,
	0x47, 0x45, 0x54, 0x53, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x1a, 0x92, 0x03, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62,
	0x61, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x3e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x54, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0x4e, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x4a, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0d, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x5f, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x0c, 0x43,
	0x52, 0x45, 0x41, 0x54, 0x45, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x22, 0xa2, 0x01, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x54,
	0x52, 0x41, 0x56, 0x45, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0c,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x1a, 0x42, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x72, 0x61,
	0x76, 0x65, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x4a, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0d, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x5f, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x0c,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x22, 0xa2, 0x01, 0x0a,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f,
	0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x0c, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x1a, 0x42, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x74, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x0d, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x0c, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x1a,
	0x16, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x46, 0x0a, 0x0d, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x56, 0x45,
	0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x54, 0x52, 0x41, 0x56, 0x45, 0x4c, 0x1a, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x81,
	0x03, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x45, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x73, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x19,
	0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x54, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x73, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x2e, 0x74, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_travel_proto_rawDescOnce sync.Once
	file_pkg_pb_travel_proto_rawDescData = file_pkg_pb_travel_proto_rawDesc
)

func file_pkg_pb_travel_proto_rawDescGZIP() []byte {
	file_pkg_pb_travel_proto_rawDescOnce.Do(func() {
		file_pkg_pb_travel_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_travel_proto_rawDescData)
	})
	return file_pkg_pb_travel_proto_rawDescData
}

var file_pkg_pb_travel_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pkg_pb_travel_proto_goTypes = []interface{}{
	(*Travel)(nil),                            // 0: travel.Travel
	(*TravelHeader)(nil),                      // 1: travel.TravelHeader
	(*GetTravelRequest)(nil),                  // 2: travel.GetTravelRequest
	(*GetTravelResponse)(nil),                 // 3: travel.GetTravelResponse
	(*GetsTravelRequest)(nil),                 // 4: travel.GetsTravelRequest
	(*GetsTravelResponse)(nil),                // 5: travel.GetsTravelResponse
	(*CreateTravelRequest)(nil),               // 6: travel.CreateTravelRequest
	(*CreateTravelResponse)(nil),              // 7: travel.CreateTravelResponse
	(*UpdateTravelRequest)(nil),               // 8: travel.UpdateTravelRequest
	(*UpdateTravelResponse)(nil),              // 9: travel.UpdateTravelResponse
	(*DeleteTravelRequest)(nil),               // 10: travel.DeleteTravelRequest
	(*DeleteTravelResponse)(nil),              // 11: travel.DeleteTravelResponse
	(*TravelHeader_Query)(nil),                // 12: travel.TravelHeader.Query
	(*TravelHeader_Sort)(nil),                 // 13: travel.TravelHeader.Sort
	(*GetTravelRequestData)(nil),              // 14: travel.GetTravelRequest.data
	(*GetTravelResponseData)(nil),             // 15: travel.GetTravelResponse.data
	(*GetsTravelResponseData)(nil),            // 16: travel.GetsTravelResponse.data
	(*GetsTravelResponseData_DataTravel)(nil), // 17: travel.GetsTravelResponse.data.DataTravel
	(*CreateTravelResponseData)(nil),          // 18: travel.CreateTravelResponse.data
	(*UpdateTravelResponseData)(nil),          // 19: travel.UpdateTravelResponse.data
	(*DeleteTravelRequestData)(nil),           // 20: travel.DeleteTravelRequest.data
	(*DeleteTravelResponseData)(nil),          // 21: travel.DeleteTravelResponse.data
}
var file_pkg_pb_travel_proto_depIdxs = []int32{
	12, // 0: travel.TravelHeader.query:type_name -> travel.TravelHeader.Query
	13, // 1: travel.TravelHeader.sort:type_name -> travel.TravelHeader.Sort
	14, // 2: travel.GetTravelRequest.GET_TRAVEL:type_name -> travel.GetTravelRequest.data
	15, // 3: travel.GetTravelResponse.GET_TRAVEL:type_name -> travel.GetTravelResponse.data
	1,  // 4: travel.GetsTravelRequest.GETS_TRAVEL:type_name -> travel.TravelHeader
	16, // 5: travel.GetsTravelResponse.GETS_TRAVEL:type_name -> travel.GetsTravelResponse.data
	0,  // 6: travel.CreateTravelRequest.CREATE_TRAVEL:type_name -> travel.Travel
	18, // 7: travel.CreateTravelResponse.CREATE_TRAVEL:type_name -> travel.CreateTravelResponse.data
	0,  // 8: travel.UpdateTravelRequest.UPDATE_TRAVEL:type_name -> travel.Travel
	19, // 9: travel.UpdateTravelResponse.UPDATE_TRAVEL:type_name -> travel.UpdateTravelResponse.data
	20, // 10: travel.DeleteTravelRequest.DELETE_TRAVEL:type_name -> travel.DeleteTravelRequest.data
	21, // 11: travel.DeleteTravelResponse.DELETE_TRAVEL:type_name -> travel.DeleteTravelResponse.data
	0,  // 12: travel.GetTravelResponse.data.data:type_name -> travel.Travel
	17, // 13: travel.GetsTravelResponse.data.data:type_name -> travel.GetsTravelResponse.data.DataTravel
	0,  // 14: travel.CreateTravelResponse.data.data:type_name -> travel.Travel
	0,  // 15: travel.UpdateTravelResponse.data.data:type_name -> travel.Travel
	4,  // 16: travel.TravelService.GetsTravel:input_type -> travel.GetsTravelRequest
	2,  // 17: travel.TravelService.GetTravel:input_type -> travel.GetTravelRequest
	6,  // 18: travel.TravelService.CreateTravel:input_type -> travel.CreateTravelRequest
	8,  // 19: travel.TravelService.UpdateTravel:input_type -> travel.UpdateTravelRequest
	10, // 20: travel.TravelService.DeleteTravel:input_type -> travel.DeleteTravelRequest
	5,  // 21: travel.TravelService.GetsTravel:output_type -> travel.GetsTravelResponse
	3,  // 22: travel.TravelService.GetTravel:output_type -> travel.GetTravelResponse
	7,  // 23: travel.TravelService.CreateTravel:output_type -> travel.CreateTravelResponse
	9,  // 24: travel.TravelService.UpdateTravel:output_type -> travel.UpdateTravelResponse
	11, // 25: travel.TravelService.DeleteTravel:output_type -> travel.DeleteTravelResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pkg_pb_travel_proto_init() }
func file_pkg_pb_travel_proto_init() {
	if File_pkg_pb_travel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_travel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Travel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TravelHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTravelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTravelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsTravelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsTravelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTravelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTravelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTravelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTravelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTravelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTravelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TravelHeader_Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TravelHeader_Sort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTravelRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTravelResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsTravelResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetsTravelResponseData_DataTravel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTravelResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTravelResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTravelRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_travel_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTravelResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_travel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_travel_proto_goTypes,
		DependencyIndexes: file_pkg_pb_travel_proto_depIdxs,
		MessageInfos:      file_pkg_pb_travel_proto_msgTypes,
	}.Build()
	File_pkg_pb_travel_proto = out.File
	file_pkg_pb_travel_proto_rawDesc = nil
	file_pkg_pb_travel_proto_goTypes = nil
	file_pkg_pb_travel_proto_depIdxs = nil
}
