version: '3.9'

services:
  travel:
    image: travel
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - fileconfig=config.json
    command:
      - serve
      - -c
      - file://config.json
    networks:
      node_net:
        ipv4_address: 172.28.2.1
    ports:
      - 8090:8090

networks:
  node_net:
    name: node_net
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  redis_data:
